% Places and names objects on front panel based on info in config file
function PlaceObjects(argin)

global basicfig basicdispfig
data = getappdata(basicfig,'protinfo');
xy = getappdata(basicdispfig,'rowscols');

%----added here by jing for resized display----
pos=get(basicdispfig,'position');
data.visible = [];
objH=[];
xy.r=[];
xy.rowcntr = 1;

xy.r(1)=pos(4)-40;
xy.r(2)=xy.r(1)-20;
xy.r(2);
i=3;
while xy.r(i-1)>0
    xy.r(i)=xy.r(i-1)-30;
    i=i+1;
end

objH(1) = uicontrol(basicdispfig,'Style','text',...
    'Tag','LabelData',...
    'Position',[xy.c(2) xy.r(1) xy.labelw1 xy.labelh1],...
    'String','Data');

objH(2) = uicontrol(basicdispfig,'Style','text',...
    'Tag','LabelLow',...
    'Position',[xy.c(3) xy.r(1) xy.labelw1 xy.labelh1],...
    'String','Low Bound');

objH(3) = uicontrol(basicdispfig,'Style','text',...
    'Tag','LabelHigh',...
    'Position',[xy.c(4) xy.r(1) xy.labelw1 xy.labelh1],...
    'String','High Bound');

objH(4) = uicontrol(basicdispfig,'Style','text',...
    'Tag','LabelIncr',...
    'Position',[xy.c(5) xy.r(1) xy.labelw1 xy.labelh1],...
    'String','Increment');

objH(5) = uicontrol(basicdispfig,'Style','text',...
    'Tag','LabelMult',...
    'Position',[xy.c(6) xy.r(1) xy.labelw1 xy.labelh1],...
    'String','Multiplier');

objH(6) = uicontrol(basicdispfig,'Style','text',...
    'Tag','LabelSpacing',...
    'Position',[xy.c(7) xy.r(1) xy.labelw1 xy.labelh1],...
    'String','Status');

objH(7) = uicontrol(basicdispfig,'Style','text',...
    'Tag','LabelStatus',...
    'Position',[xy.c(8) xy.r(1) xy.labelw1 xy.labelh1],...
    'String','Spacing');


for i = 1:size(data.configinfo,2)

    i1 = strmatch('MOTION_TYPE',{char(data.configinfo.name)},'exact');
    if data.configinfo(i1).parameters == 1 % should be 1 interval
        if isfield(data.configinfo(i).parameters,'moog')
            if length(data.configinfo(i).parameters.moog) >= 3
                inds = 1:3;
            else
                inds = 1;
            end
        else
            if length(data.configinfo(i).parameters) >= 2
                inds = 1:length(data.configinfo(i).parameters);
            else
                inds = 1;
            end
        end
    elseif data.configinfo(i1).parameters == 3 % should be 2 interval
        if isfield(data.configinfo(i).parameters,'moog')
            inds = 1:length(data.configinfo(i).parameters.moog);
        else
            inds = 1:length(data.configinfo(i).parameters);
        end
    end

    rowstr = data.configinfo(i).nice_name;
    tagstr = data.configinfo(i).name;
    genval = data.configinfo(i).vectgen;
    statusval = data.configinfo(i).status;
    catval = data.configinfo(i).category;
    tooltipstr = data.configinfo(i).tool_tip;
    if isfield(data.configinfo(i).parameters,'moog')
        lowstr = [num2str(data.configinfo(i).low_bound.moog(inds)), ' ',...
            num2str(data.configinfo(i).low_bound.openGL(inds))];
        highstr = [num2str(data.configinfo(i).high_bound.moog(inds)), ' ',...
            num2str(data.configinfo(i).high_bound.openGL(inds))];
        incrstr = [num2str(data.configinfo(i).increment.moog(inds)), ' ',...
            num2str(data.configinfo(i).increment.openGL(inds))];
        multstr = [num2str(data.configinfo(i).multiplier.moog(inds)), ' ',...
            num2str(data.configinfo(i).multiplier.openGL(inds))];
        datastr = [num2str(data.configinfo(i).parameters.moog(inds)), ' ',...
            num2str(data.configinfo(i).parameters.openGL(inds))];
    else
        lowstr = num2str(data.configinfo(i).low_bound(inds));
        highstr = num2str(data.configinfo(i).high_bound(inds));
        incrstr = num2str(data.configinfo(i).increment(inds));
        multstr = num2str(data.configinfo(i).multiplier(inds));
        datastr = num2str(data.configinfo(i).parameters(inds));
    end

    %----added here by jing for category<32(Motion Option)---
    if catval<32
        catval=0;
    end

    %     Catval is the category number, chooses which category of parameters
    %     in shown in this display.... < 256 should be any timing parameters
    %     that are active for this config file
    if catval == argin
        data.visible = [data.visible i];
        if size(xy.r,2)>xy.rowcntr%--------jing------
            %eval([ 'row = xy.r' num2str(xy.rowcntr) ';']);
            xy.rowcntr = xy.rowcntr + 1;
            row=xy.r(xy.rowcntr);

            tag = [tagstr '-Label'];
            h1 = uicontrol(basicdispfig,'Style','text',...
                'Tag',tag,...
                'Position',[xy.c(1) row 2.8*xy.textw1 xy.texth1],...
                'String',rowstr,...
                'HorizontalAlignment','left',...
                'ToolTipString',tooltipstr);

            tag = [tagstr '-DataText'];
            if statusval == 1 || statusval == 0
                indstr = datastr;
            else
                indstr = [lowstr ':' incrstr ':' highstr];
            end
            h2 = uicontrol(basicdispfig,'Style','edit',...
                'Tag',tag,...
                'Position',[xy.c(2) row 1.7*xy.textw1 xy.texth1],...
                'String',indstr,...
                'BackgroundColor','white',...
                'Callback','updateconfig(gcbo)',...
                'ToolTipString',tooltipstr);

            tag = [tagstr '-LowText'];
            h3 = uicontrol(basicdispfig,'Style','edit',...
                'Tag',tag,...
                'Position',[xy.c(3) row 1.3*xy.textw1 xy.texth1],...
                'String',lowstr,...
                'BackgroundColor','white',...
                'Callback','updateconfig(gcbo)',...
                'ToolTipString',tooltipstr);


            tag = [tagstr '-HighText'];
            h4 = uicontrol(basicdispfig,'Style','edit',...
                'Tag',tag,...
                'Position',[xy.c(4) row 1.3*xy.textw1 xy.texth1],...
                'String',highstr,...
                'BackgroundColor','white',...
                'Callback','updateconfig(gcbo)',...
                'ToolTipString',tooltipstr);


            tag = [tagstr '-IncrText'];
            h5 = uicontrol(basicdispfig,'Style','edit',...
                'Tag',tag,...
                'Position',[xy.c(5) row 1.3*xy.textw1 xy.texth1],...
                'String',incrstr,...
                'BackgroundColor','white',...
                'Callback','updateconfig(gcbo)',...
                'ToolTipString',tooltipstr);


            tag = [tagstr '-MultText'];
            h6 = uicontrol(basicdispfig,'Style','edit',...
                'Tag',tag,...
                'Position',[xy.c(6) row 1.3*xy.textw1 xy.texth1],...
                'String',multstr,...
                'BackgroundColor','white',...
                'Callback','updateconfig(gcbo)',...
                'ToolTipString',tooltipstr);



            tag = [tagstr '-SpacingPopupMenu'];
            h8 = uicontrol(basicdispfig,'Style','popupmenu',...
                'Tag',tag,...
                'Position',[xy.c(8) row 1.3*xy.textw1 xy.texth1],...
                'String',['Linear';'Log   ';'Custom'],...
                'HorizontalAlignment','left',...
                'Value',genval+1,...
                'BackgroundColor','white',...
                'Callback','updateconfig(gcbo)',...
                'ToolTipString',tooltipstr);


            if statusval == 0
                %             disp([rowstr ' has been choosen to be editable,'...
                %             ' but is a fixed value and should not be altered'])
                tag = [tagstr '-StatusPopupMenu'];
                h7 = uicontrol(basicdispfig,'Style','text',...
                    'Tag',tag,...
                    'Position',[xy.c(7) row 1.3*xy.textw1 xy.texth1],...
                    'String','FIXED VALUE',...
                    'ToolTipString',tooltipstr);
                set(findobj('Tag',[tagstr '-DataText']),'Enable','Inactive');
            else
                tag = [tagstr '-StatusPopupMenu'];
                h7 = uicontrol(basicdispfig,'Style','popupmenu',...
                    'Tag',tag,...
                    'Position',[xy.c(7) row 1.3*xy.textw1 xy.texth1],...
                    'String',['Static     ';'Varying    ';'AcrossStair';'WithinStair'],...
                    'Value',statusval,...
                    'BackgroundColor','white',...
                    'Callback','updateconfig(gcbo)',...
                    'ToolTipString',tooltipstr);
            end

            tag = [tagstr '-EditVarying'];
            h9 = uicontrol(basicdispfig,'Style','pushbutton',...
                'Tag',tag,...
                'Position',[xy.c(9) row 1.3*xy.textw1 xy.texth1],...
                'String','Edit Varying',...
                'HorizontalAlignment','left',...
                'Callback','BasicInterface(''EditButton_Callback'',gcbo,[],guidata(gcbo))',...
                'ToolTipString',tooltipstr);

            objH=[objH h1 h2 h3 h4 h5 h6 h7 h8 h9];

            % Disable all non relavent variable parameters
            if data.configinfo(i).status <= 1 % Static or Fixed
                set(findobj(basicdispfig,'Tag',[tagstr '-LowText']),'Enable','off');
                set(findobj(basicdispfig,'Tag',[tagstr '-HighText']),'Enable','off');
                set(findobj(basicdispfig,'Tag',[tagstr '-MultText']),'Enable','off');
                set(findobj(basicdispfig,'Tag',[tagstr '-IncrText']),'Enable','off');
                set(findobj(basicdispfig,'Tag',[tagstr '-SpacingPopupMenu']),'Enable','off');
                set(findobj(basicdispfig,'Tag',[tagstr '-DataText']),'String',datastr);
            else % Varying
                set(findobj(basicdispfig,'Tag',[tagstr '-LowText']),'Enable','on');
                set(findobj(basicdispfig,'Tag',[tagstr '-HighText']),'Enable','on');
                set(findobj(basicdispfig,'Tag',[tagstr '-SpacingPopupMenu']),'Enable','on');
                set(findobj(basicdispfig,'Tag',[tagstr '-DataText']),'String',...
                    [lowstr ':' incrstr ':' highstr]);
                if data.configinfo(i).vectgen == 0 % Linear Spacing
                    set(findobj(basicdispfig,'Tag',[data.configinfo(i).name '-MultText']),...
                        'Enable','off');
                    set(findobj(basicdispfig,'Tag',[data.configinfo(i).name '-IncrText']),...
                        'Enable','on');
                elseif data.configinfo(i).vectgen == 1 % Log Spacing
                    set(findobj(basicdispfig,'Tag',[data.configinfo(i).name '-MultText']),...
                        'Enable','on');
                    set(findobj(basicdispfig,'Tag',[data.configinfo(i).name '-IncrText']),...
                        'Enable','off');
                elseif data.configinfo(i).vectgen == 2 % Custom vectot generation
                    set(findobj(basicdispfig,'Tag',[data.configinfo(i).name '-MultText']),...
                        'Enable','off');
                    set(findobj(basicdispfig,'Tag',[data.configinfo(i).name '-IncrText']),...
                        'Enable','off');
                else
                    disp('Vector Generation parameter does not match any known format')
                end
            end
        end
    else
        % do not put any control for particular variable on screen
    end
end

setappdata(basicfig,'protinfo',data);
%-----added by jing-----
setappdata(basicdispfig,'rowscols',xy);
setappdata(basicdispfig,'subhandles',objH);


