function EyeOptionsWindow
global basicfig eyeOptfig

data = getappdata(basicfig,'protinfo'); 
chanInfo = data.channels(cell2mat({data.channels.active})==1); 

eyeWinData = getappdata(basicfig, 'eyeWinData');

eyecode = eyeWinData.eyecode;
zoom1 = eyeWinData.zoomFactorPos;
zoom2 = eyeWinData.zoomFactorVergence;

totalChan = length(chanInfo);

tempIndex = strmatch('EYE_OFFSETS',{char(data.configinfo.name)},'exact');
eyeoffsetDatastr = num2str(data.configinfo(tempIndex).parameters);

tempIndex = strmatch('HEAD_CENTER',{char(data.configinfo.name)},'exact');
headcenterDatastr =num2str(data.configinfo(tempIndex).parameters);


set(0,'Units','centimeters');
scnsize = get(0,'ScreenSize');
lw = 1.3;
lh = 0.4;
pos  = [2*scnsize(3)-7.2, scnsize(4)-10.5, 7, 10];
posl = [0.2 pos(4)-5*lh lw lh];
posr = [0.2 pos(4)/2 lw lh];
calstr = 0;
horlabelstr = {'Horizontal' 'Vertical' 'Torsion'};
verlabelstr = {'Offset' 'Gain' 'Coupling'};


eyeOptfig = figure('Units','centimeters',...
                   'Position',pos,...
                   'Name','Eye Options',...
                   'NumberTitle','off',...
                   'MenuBar','none',...
                   'Color',[0.831 0.816 0.784]);
                 
uicontrol(eyeOptfig,'Units','centimeters',...
                    'Style','text',...
                    'Position',[0.2 pos(4)-lh 2.8*lw lh],...
                    'String','Software Calibration Status:',...
                    'HorizontalAlignment', 'Left',...
                    'BackgroundColor',[0.831 0.816 0.784]);
                
uicontrol(eyeOptfig,'Units','centimeters',...
                    'Style','edit',...
                    'Tag','calEdit',...
                    'Position',[3*lw pos(4)-lh lw lh],...
                    'String',calstr,...
                    'BackgroundColor','white',...
                    'Callback',{@calEdit_callback,gcbo},...
                    'ToolTipString','0=OFF, 1=ON');
                
uicontrol(eyeOptfig,'Units','centimeters',...
                    'Style','text',...
                    'Position',[0.2 pos(4)-3*lh 1.5 lh],...
                    'String','Eye Code:',...
                    'HorizontalAlignment', 'Left',...
                    'BackgroundColor',[0.831 0.816 0.784]);
                
uicontrol(eyeOptfig,'Units','centimeters',...
                    'Style','edit',...
                    'Tag','eyecodeEdit',...
                    'Position',[1.7 pos(4)-3*lh lw lh],...
                    'String',num2str(eyecode),...
                    'BackgroundColor','white',...
                    'Callback',{@eyecodeEdit_callback,gcbo},...
                    'ToolTipString','0=Left Eye, 1=Right Eye, 2=Both Eye');                
                              
uicontrol(eyeOptfig,'Units','centimeters',...
                    'Style','text',...
                    'Position',posl,...
                    'String','Left Eye:',...
                    'HorizontalAlignment', 'Left',...
                    'BackgroundColor',[0.831 0.816 0.784]);
                
uicontrol(eyeOptfig,'Units','centimeters',...
                    'Style','text',...
                    'Position',posr,...
                    'String','Right Eye:',...
                    'HorizontalAlignment', 'Left',...
                    'BackgroundColor',[0.831 0.816 0.784]);
                
%left eye channel parameter list               
for i=1:3    %paramater title
    uicontrol(eyeOptfig,'Units','centimeters',...
                        'Style','text',...
                        'Position',[posl(1) posl(2)-i*(lh+0.2) lw lh],...
                        'String',verlabelstr(i),...
                        'HorizontalAlignment', 'Right',...
                        'BackgroundColor',[0.831 0.816 0.784]);   
                    
    uicontrol(eyeOptfig,'Units','centimeters',...
                        'Style','text',...
                        'Position',[posl(1)+i*(lw+0.2) posl(2)-0.5*lh lw lh],...
                        'String',horlabelstr(i),...
                        'BackgroundColor',[0.831 0.816 0.784]);
end
 

for i=1:3  %paramater data
    offsetTagstr = '-offset';
    gainTagstr = '-gain';
    couplingTagstr = '-coupling';
    offsetDatastr = '';
    gainDatastr = '';
    couplingDatastr = '';
    for j=1:totalChan
        if chanInfo(j).chanNum == i 
            offsetTagstr = [chanInfo(j).name offsetTagstr];
            gainTagstr = [chanInfo(j).name gainTagstr];
            couplingTagstr = [chanInfo(j).name couplingTagstr];
            offsetDatastr = num2str(chanInfo(j).offset);
            gainDatastr = num2str(chanInfo(j).scale);
            couplingDatastr = num2str(chanInfo(j).coupling);
        end
    end
    uicontrol(eyeOptfig,'Units','centimeters',...
                        'Style','edit',...
                        'Tag',offsetTagstr,...
                        'Position',[posl(1)+i*(lw+0.2) posl(2)-(lh+0.2) lw lh],...
                        'String',offsetDatastr,...
                        'BackgroundColor','white',...
                        'Callback',{@updatechanInfo,gcbo});
    uicontrol(eyeOptfig,'Units','centimeters',...
                        'Style','edit',...
                        'Tag',gainTagstr,...
                        'Position',[posl(1)+i*(lw+0.2) posl(2)-2*(lh+0.2) lw lh],...
                        'String',gainDatastr,...
                        'BackgroundColor','white',...
                        'Callback',{@updatechanInfo,gcbo}');
    uicontrol(eyeOptfig,'Units','centimeters',...
                        'Style','edit',...
                        'Tag',couplingTagstr,...
                        'Position',[posl(1)+i*(lw+0.2) posl(2)-3*(lh+0.2) lw lh],...
                        'String',couplingDatastr,...
                        'BackgroundColor','white',...
                        'Callback',{@updatechanInfo,gcbo});
end

%right eye channel parameter list               
for i=1:3  %paramater title
    uicontrol(eyeOptfig,'Units','centimeters',...
                        'Style','text',...
                        'Position',[posr(1) posr(2)-i*(lh+0.2) lw lh],...
                        'String',verlabelstr(i),...
                        'HorizontalAlignment', 'Right',...
                        'BackgroundColor',[0.831 0.816 0.784]);    
    uicontrol(eyeOptfig,'Units','centimeters',...
                        'Style','text',...
                        'Position',[posr(1)+i*(lw+0.2) posr(2)-0.5*lh lw lh],...
                        'String',horlabelstr(i),...
                        'BackgroundColor',[0.831 0.816 0.784]);   
end

for i=1:3   %paramater data
    offsetTagstr = '-offset';
    gainTagstr = '-gain';
    couplingTagstr = '-coupling';
    offsetDatastr = '';
    gainDatastr = '';
    couplingDatastr = '';
    for j=1:totalChan
        if chanInfo(j).chanNum == i+3 
            offsetTagstr = [chanInfo(j).name offsetTagstr];
            gainTagstr = [chanInfo(j).name gainTagstr];
            couplingTagstr = [chanInfo(j).name couplingTagstr];
            offsetDatastr = num2str(chanInfo(j).offset);
            gainDatastr = num2str(chanInfo(j).scale);
            couplingDatastr = num2str(chanInfo(j).coupling);
        end
    end
    uicontrol(eyeOptfig,'Units','centimeters',...
                        'Style','edit',...
                        'Tag',offsetTagstr ,...
                        'Position',[posr(1)+i*(lw+0.2) posr(2)-(lh+0.2) lw lh],...
                        'String',offsetDatastr,...
                        'BackgroundColor','white',...
                        'Callback',{@updatechanInfo,gcbo});   
    uicontrol(eyeOptfig,'Units','centimeters',...
                        'Style','edit',...
                        'Tag',gainTagstr,...
                        'Position',[posr(1)+i*(lw+0.2) posr(2)-2*(lh+0.2) lw lh],...
                        'String',gainDatastr,...
                        'BackgroundColor','white',...
                        'Callback',{@updatechanInfo,gcbo}); 
    uicontrol(eyeOptfig,'Units','centimeters',...
                        'Style','edit',...
                        'Tag',couplingTagstr,...
                        'Position',[posr(1)+i*(lw+0.2) posr(2)-3*(lh+0.2) lw lh],...
                        'String',couplingDatastr,...
                        'BackgroundColor','white',...
                        'Callback',{@updatechanInfo,gcbo}); 
end   

uicontrol(eyeOptfig,'Units','centimeters',...
                    'Style','text',...
                    'Position',[posr(1) 2.5-lh 1.5*lw lh],...
                    'String','Zoom Factor:',...
                    'HorizontalAlignment', 'Left',...
                    'BackgroundColor',[0.831 0.816 0.784]);                
uicontrol(eyeOptfig,'Units','centimeters',...
                    'Style','text',...
                    'Position',[posr(1) 2.5-2*lh 1.5*lw lh],...
                    'String','Eye Position',...
                    'HorizontalAlignment', 'Right',...
                    'BackgroundColor',[0.831 0.816 0.784]);    
uicontrol(eyeOptfig,'Units','centimeters',...
                    'Style','edit',...
                    'Tag','zoomposEdit',...
                    'Position',[posr(1)+1.5*lw+0.2 2.5-2*lh lw/2 lh],...
                    'String',num2str(zoom1),...
                    'BackgroundColor','white',...
                    'Callback',{@zoomposEdit_callback, gcbo});
uicontrol(eyeOptfig,'Units','centimeters',...
                    'Style','text',...
                    'Position',[posr(1)+2.5*lw 2.5-2*lh lw lh],...
                    'String','Vergence',...
                    'HorizontalAlignment', 'Right',...
                    'BackgroundColor',[0.831 0.816 0.784]);      
uicontrol(eyeOptfig,'Units','centimeters',...
                    'Style','edit',...
                    'Tag','zoomverEdit',...
                    'Position',[posr(1)+3.5*lw+0.2 2.5-2*lh lw/2 lh],...
                    'String',num2str(zoom2),...
                    'BackgroundColor','white',...
                    'Callback',{@zoomverEdit_callback, gcbo});
                
uicontrol(eyeOptfig,'Units','centimeters',...
                    'Style','text',...
                    'Position',[posr(1) 2.5-4*lh 1.4*lw lh],...
                    'String','Eye Offset',...
                    'HorizontalAlignment','Left',...
                    'BackgroundColor',[0.831 0.816 0.784]);        
uicontrol(eyeOptfig,'Units','centimeters',...
                    'Style','edit',...
                    'Tag','eyeoffsetEdit',...
                    'Position',[posr(1)+1.5*lw 2.5-4*lh 2.5*lw lh],...
                    'String',eyeoffsetDatastr,...
                    'BackgroundColor','white',...
                    'Callback',{@eyeoffsetEdit_callback, gcbo});                
                
uicontrol(eyeOptfig,'Units','centimeters',...
                    'Style','text',...
                    'Position',[posr(1) 2.4-5*lh 1.4*lw lh],...
                    'String','Head Center',...
                    'HorizontalAlignment', 'Left',...
                    'BackgroundColor',[0.831 0.816 0.784]);    
uicontrol(eyeOptfig,'Units','centimeters',...
                    'Style','edit',...
                    'Tag','headcenterEdit',...
                    'Position',[posr(1)+1.5*lw 2.4-5*lh 2.5*lw lh],...
                    'String',headcenterDatastr,...
                    'BackgroundColor','white',...
                    'Callback',{@headcenterEdit_callback, gcbo});
 
 
                

function calEdit_callback(hobject, event_data,handles)

function eyecodeEdit_callback(hobject, event_data,handles)
global basicfig

eyeWinData = getappdata(basicfig, 'eyeWinData');
eyeWinData.eyecode = str2num(get(hobject,'String'));
setappdata(basicfig, 'eyeWinData',eyeWinData);


function zoomposEdit_callback(hobject, event_data,handles)
global basicfig

eyeWinData = getappdata(basicfig, 'eyeWinData');
appHandle = getappdata(basicfig, 'posViewHandle');

zoomFactor = str2num(get(hobject,'String'));
eyeWinData.zoomFactorPos = zoomFactor;

set(appHandle.axex1,'XLim',[-30*zoomFactor 30*zoomFactor],'YLim',[-30*zoomFactor 30*zoomFactor]);   
setappdata(basicfig, 'eyeWinData',eyeWinData);


function zoomverEdit_callback(hobject, event_data,handles)
global basicfig

eyeWinData = getappdata(basicfig, 'eyeWinData');
appHandle = getappdata(basicfig, 'posViewHandle');

zoomFactor = str2num(get(hobject,'String'));
eyeWinData.zoomFactorVergence = zoomFactor;

set(appHandle.axex2,'XLim',[-30*zoomFactor 30*zoomFactor],'YLim',[-30*zoomFactor 30*zoomFactor]);  
setappdata(basicfig, 'eyeWinData',eyeWinData);


function eyeoffsetEdit_callback(hobject, event_data,handles)
global basicfig

data = getappdata(basicfig,'protinfo'); 
tempIndex = strmatch('EYE_OFFSETS',{char(data.configinfo.name)},'exact');
data.configinfo(tempIndex).parameters = str2num(get(hobject,'String'));
setappdata(basicfig,'protinfo', data);

function headcenterEdit_callback(hobject, event_data,handles)
global basicfig

data = getappdata(basicfig,'protinfo'); 
tempIndex = strmatch('HEAD_CENTER',{char(data.configinfo.name)},'exact');
data.configinfo(tempIndex).parameters = str2num(get(hobject,'String'));
setappdata(basicfig,'protinfo', data);

function updatechanInfo(hobject, event_data,handles)
global basicfig 

data = getappdata(basicfig,'protinfo');
tag = get(hobject,'Tag');

channame = strtok(tag,'-');
valname = tag(strfind(tag,'-')+1:end);

i = strmatch(channame, {char(data.channels.name)}, 'exact');

if strmatch(valname, 'offset', 'exact')
    val = str2num(get(hobject,'String'));
    data.channels(i).offset = val;
end

if strmatch(valname, 'gain', 'exact')
    val = str2num(get(hobject,'String'));
    data.channels(i).scale = val;
end

if strmatch(valname, 'coupling', 'exact')
    val = str2num(get(hobject,'String'));
    data.channels(i).coupling = val;
end

setappdata(basicfig,'protinfo', data);             
                    
                    
                    
    