function eyeCalibrationOptionsWindow
global eyeCalfig eyeOptfig

data = getappdata(eyeCalfig,'protinfo'); 
chanInfo = data.channels(cell2mat({data.channels.active})==1); 

eyeWinData = getappdata(eyeCalfig, 'eyeWinData');

zoom1 = eyeWinData.zoomFactorPos;
zoom2 = eyeWinData.zoomFactorVergence;

totalChan = length(chanInfo);

set(0,'Units','centimeters');
scnsize = get(0,'ScreenSize');
lw = 1.3;
lh = 0.4;
%pos  = [2*scnsize(3)-7.2, scnsize(4)-10.5, 7, 10];
pos  = [scnsize(3)-7.2, scnsize(4)-14.5, 7, 10];
posl = [0.2 pos(4)-5*lh lw lh];
posr = [0.2 pos(4)/2 lw lh];
calstr = 0;
horlabelstr = {'Horizontal' 'Vertical' 'Torsion'};
verlabelstr = {'Offset' 'Gain' 'Coupling'};


eyeOptfig = figure('Units','centimeters',...
                   'Position',pos,...
                   'Name','Eye Options',...
                   'NumberTitle','off',...
                   'MenuBar','none',...
                   'Color',[0.831 0.816 0.784]);
                              
uicontrol(eyeOptfig,'Units','centimeters',...
                    'Style','text',...
                    'Position',posl,...
                    'String','Left Eye:',...
                    'HorizontalAlignment', 'Left',...
                    'BackgroundColor',[0.831 0.816 0.784]);
                
uicontrol(eyeOptfig,'Units','centimeters',...
                    'Style','text',...
                    'Position',posr,...
                    'String','Right Eye:',...
                    'HorizontalAlignment', 'Left',...
                    'BackgroundColor',[0.831 0.816 0.784]);
                
%left eye channel parameter list               
for i=1:3    %paramater title
    uicontrol(eyeOptfig,'Units','centimeters',...
                        'Style','text',...
                        'Position',[posl(1) posl(2)-i*(lh+0.2) lw lh],...
                        'String',verlabelstr(i),...
                        'HorizontalAlignment', 'Right',...
                        'BackgroundColor',[0.831 0.816 0.784]);   
                    
    uicontrol(eyeOptfig,'Units','centimeters',...
                        'Style','text',...
                        'Position',[posl(1)+i*(lw+0.2) posl(2)-0.5*lh lw lh],...
                        'String',horlabelstr(i),...
                        'BackgroundColor',[0.831 0.816 0.784]);
end
 

for i=1:3  %paramater data
    offsetTagstr = '-offset';
    gainTagstr = '-gain';
    couplingTagstr = '-coupling';
    offsetDatastr = '';
    gainDatastr = '';
    couplingDatastr = '';
    for j=1:totalChan
        if chanInfo(j).chanNum == i 
            offsetTagstr = [chanInfo(j).name offsetTagstr];
            gainTagstr = [chanInfo(j).name gainTagstr];
            couplingTagstr = [chanInfo(j).name couplingTagstr];
            offsetDatastr = num2str(chanInfo(j).offset);
            gainDatastr = num2str(chanInfo(j).scale);
            couplingDatastr = num2str(chanInfo(j).coupling);
        end
    end
    uicontrol(eyeOptfig,'Units','centimeters',...
                        'Style','edit',...
                        'Tag',offsetTagstr,...
                        'Position',[posl(1)+i*(lw+0.2) posl(2)-(lh+0.2) lw lh],...
                        'String',offsetDatastr,...
                        'BackgroundColor','white',...
                        'Callback',{@updatechanInfo,gcbo});
    uicontrol(eyeOptfig,'Units','centimeters',...
                        'Style','edit',...
                        'Tag',gainTagstr,...
                        'Position',[posl(1)+i*(lw+0.2) posl(2)-2*(lh+0.2) lw lh],...
                        'String',gainDatastr,...
                        'BackgroundColor','white',...
                        'Callback',{@updatechanInfo,gcbo}');
    uicontrol(eyeOptfig,'Units','centimeters',...
                        'Style','edit',...
                        'Tag',couplingTagstr,...
                        'Position',[posl(1)+i*(lw+0.2) posl(2)-3*(lh+0.2) lw lh],...
                        'String',couplingDatastr,...
                        'BackgroundColor','white',...
                        'Callback',{@updatechanInfo,gcbo});
end

%right eye channel parameter list               
for i=1:3  %paramater title
    uicontrol(eyeOptfig,'Units','centimeters',...
                        'Style','text',...
                        'Position',[posr(1) posr(2)-i*(lh+0.2) lw lh],...
                        'String',verlabelstr(i),...
                        'HorizontalAlignment', 'Right',...
                        'BackgroundColor',[0.831 0.816 0.784]);    
    uicontrol(eyeOptfig,'Units','centimeters',...
                        'Style','text',...
                        'Position',[posr(1)+i*(lw+0.2) posr(2)-0.5*lh lw lh],...
                        'String',horlabelstr(i),...
                        'BackgroundColor',[0.831 0.816 0.784]);   
end

for i=1:3   %paramater data
    offsetTagstr = '-offset';
    gainTagstr = '-gain';
    couplingTagstr = '-coupling';
    offsetDatastr = '';
    gainDatastr = '';
    couplingDatastr = '';
    for j=1:totalChan
        if chanInfo(j).chanNum == i+3 
            offsetTagstr = [chanInfo(j).name offsetTagstr];
            gainTagstr = [chanInfo(j).name gainTagstr];
            couplingTagstr = [chanInfo(j).name couplingTagstr];
            offsetDatastr = num2str(chanInfo(j).offset);
            gainDatastr = num2str(chanInfo(j).scale);
            couplingDatastr = num2str(chanInfo(j).coupling);
        end
    end
    uicontrol(eyeOptfig,'Units','centimeters',...
                        'Style','edit',...
                        'Tag',offsetTagstr ,...
                        'Position',[posr(1)+i*(lw+0.2) posr(2)-(lh+0.2) lw lh],...
                        'String',offsetDatastr,...
                        'BackgroundColor','white',...
                        'Callback',{@updatechanInfo,gcbo});   
    uicontrol(eyeOptfig,'Units','centimeters',...
                        'Style','edit',...
                        'Tag',gainTagstr,...
                        'Position',[posr(1)+i*(lw+0.2) posr(2)-2*(lh+0.2) lw lh],...
                        'String',gainDatastr,...
                        'BackgroundColor','white',...
                        'Callback',{@updatechanInfo,gcbo}); 
    uicontrol(eyeOptfig,'Units','centimeters',...
                        'Style','edit',...
                        'Tag',couplingTagstr,...
                        'Position',[posr(1)+i*(lw+0.2) posr(2)-3*(lh+0.2) lw lh],...
                        'String',couplingDatastr,...
                        'BackgroundColor','white',...
                        'Callback',{@updatechanInfo,gcbo}); 
end   

uicontrol(eyeOptfig,'Units','centimeters',...
                    'Style','text',...
                    'Position',[posr(1) 2.5-lh 1.5*lw lh],...
                    'String','Zoom Factor:',...
                    'HorizontalAlignment', 'Left',...
                    'BackgroundColor',[0.831 0.816 0.784]);                
uicontrol(eyeOptfig,'Units','centimeters',...
                    'Style','text',...
                    'Position',[posr(1) 2.5-2*lh 1.5*lw lh],...
                    'String','Eye Position',...
                    'HorizontalAlignment', 'Right',...
                    'BackgroundColor',[0.831 0.816 0.784]);    
uicontrol(eyeOptfig,'Units','centimeters',...
                    'Style','edit',...
                    'Tag','zoomposEdit',...
                    'Position',[posr(1)+1.5*lw+0.2 2.5-2*lh lw/2 lh],...
                    'String',num2str(zoom1),...
                    'BackgroundColor','white',...
                    'Callback',{@zoomposEdit_callback, gcbo});
uicontrol(eyeOptfig,'Units','centimeters',...
                    'Style','text',...
                    'Position',[posr(1)+2.5*lw 2.5-2*lh lw lh],...
                    'String','Vergence',...
                    'HorizontalAlignment', 'Right',...
                    'BackgroundColor',[0.831 0.816 0.784]);      
uicontrol(eyeOptfig,'Units','centimeters',...
                    'Style','edit',...
                    'Tag','zoomverEdit',...
                    'Position',[posr(1)+3.5*lw+0.2 2.5-2*lh lw/2 lh],...
                    'String',num2str(zoom2),...
                    'BackgroundColor','white',...
                    'Callback',{@zoomverEdit_callback, gcbo});
 

function zoomposEdit_callback(hobject, event_data,handles)
global eyeCalfig

eyeWinData = getappdata(eyeCalfig, 'eyeWinData');
appHandle = getappdata(eyeCalfig, 'posViewHandle');

zoomFactor = str2num(get(hobject,'String'));
eyeWinData.zoomFactorPos = zoomFactor;

set(appHandle.axex1,'XLim',[-30*zoomFactor 30*zoomFactor],'YLim',[-30*zoomFactor 30*zoomFactor]);   
setappdata(eyeCalfig, 'eyeWinData',eyeWinData);


function zoomverEdit_callback(hobject, event_data,handles)
global eyeCalfig

eyeWinData = getappdata(eyeCalfig, 'eyeWinData');
appHandle = getappdata(eyeCalfig, 'posViewHandle');

zoomFactor = str2num(get(hobject,'String'));
eyeWinData.zoomFactorVergence = zoomFactor;

set(appHandle.axex2,'XLim',[-30*zoomFactor 30*zoomFactor],'YLim',[-30*zoomFactor 30*zoomFactor]);  
setappdata(eyeCalfig, 'eyeWinData',eyeWinData);


function updatechanInfo(hobject, event_data,handles)
global eyeCalfig 

data = getappdata(eyeCalfig,'protinfo');
tag = get(hobject,'Tag');

channame = strtok(tag,'-');
valname = tag(strfind(tag,'-')+1:end);

i = strmatch(channame, {char(data.channels.name)}, 'exact');

if strmatch(valname, 'offset', 'exact')
    val = str2num(get(hobject,'String'));
    data.channels(i).offset = val;
end

if strmatch(valname, 'gain', 'exact')
    val = str2num(get(hobject,'String'));
    data.channels(i).scale = val;
end

if strmatch(valname, 'coupling', 'exact')
    val = str2num(get(hobject,'String'));
    data.channels(i).coupling = val;
end

setappdata(eyeCalfig,'protinfo', data);             
                    
                    
                    
    