function EyeCalibration
global eyeCalfig paths 

if isempty(findobj('Name','Eye Calibration'))
    set(0,'Units','centimeters')
    pos = get(0,'ScreenSize');
    posSmoothingstr = 5;
    offsetStepstr = 0.5;
    gainStepstr = 1;
    targStepstr = 5;
    durstr = 2;
    winstr = 5;
    eyecodeStr = {'Left' 'Right'};
    headCenterstr = '0 0 0';
    eyeOffsetstr = '0 0 0';
    ioDiststr = 0;
    prots = 'Calibration_6chan.mat';

    eyeCalfig = figure('Units','centimeters',...
        'Position',[0.5 pos(4)/2-5 10 15 ],...
        'Color',[0.831 0.816 0.784],...
        'Name','Eye Calibration',...
        'NumberTitle','off',...
        'MenuBar','none',...
        'CloseRequestFcn',{@EyeCalibration_CloseRequestFcn});
    figpos = get(eyeCalfig,'position');
    
    uicontrol(eyeCalfig,'Units','centimeters',...
        'Style','text',...
        'Position',[1 figpos(4)-0.6 3 0.5],...
        'String','Protocols:',...
        'HorizontalAlignment', 'Left');

    uicontrol(eyeCalfig,'Units','centimeters',...
        'Style','edit',...
        'Tag','ProtEdit',...
        'Position',[1 figpos(4)-1 4 0.5],...
        'String',prots,...
        'Enable','Off',...
        'BackgroundColor','white');
    uicontrol(eyeCalfig,'Units','centimeters',...
        'Style','text',...
        'Position',[6 figpos(4)-0.6 2 0.5],...
        'String','Eye Code:',...
        'HorizontalAlignment', 'Left');
    uicontrol(eyeCalfig,'Units','centimeters',...
        'Style','popupmenu',...
        'Tag','EyecodePopupMenu',...
        'Position',[6 figpos(4)-1 2.5 0.5],...
        'String',eyecodeStr,...
        'Value',size(eyecodeStr,1),...
        'BackgroundColor','white',...
        'Callback',{@eyecodePopupMenu_callback});
    uicontrol(eyeCalfig,'Units','centimeters',...
        'Style','pushbutton',...
        'Tag','WatchEyeButton',...
        'Position',[6 figpos(4)-2 2 0.5],...
        'String','Watch Eye',...
        'Callback',{@watchEyeButton_callback});
    uicontrol(eyeCalfig,'Units','centimeters',...
        'Style','text',...
        'Position',[1 figpos(4)-2 3 0.5],...
        'String','Position Smoothing (pt):',...
        'BackgroundColor',[0.831 0.816 0.784],...
        'HorizontalAlignment', 'Right');
    uicontrol(eyeCalfig,'Units','centimeters',...
        'Style','edit',...
        'Tag','posSmoothEdit',...
        'Position',[4.2 figpos(4)-2 1 0.5],...
        'String',posSmoothingstr,...
        'Callback',{@posSmoothEdit_callback},...
        'BackgroundColor','white');
    uicontrol(eyeCalfig,'Units','centimeters',...
        'Style','pushbutton',...
        'Tag','offsetUpButton',...
        'Position',[2 figpos(4)-3.4 1 0.5],...
        'String','UP',...
        'Callback',{@offsetUpButton_callback});
    uicontrol(eyeCalfig,'Units','centimeters',...
        'Style','text',...
        'Position',[2 figpos(4)-4 1 0.5],...
        'String','Offset',...
        'BackgroundColor',[0.831 0.816 0.784]);
    uicontrol(eyeCalfig,'Units','centimeters',...
        'Style','pushbutton',...
        'Tag','offsetDownButton',...
        'Position',[2 figpos(4)-4.4 1 0.5],...
        'String','Down',...
        'Callback',{@offsetDownButton_callback});
    uicontrol(eyeCalfig,'Units','centimeters',...
        'Style','pushbutton',...
        'Tag','offsetLeftButton',...
        'Position',[0.9 figpos(4)-3.9 1 0.5],...
        'String','Left',...
        'Callback',{@offsetLeftButton_callback});
    uicontrol(eyeCalfig,'Units','centimeters',...
        'Style','pushbutton',...
        'Tag','offsetRightButton',...
        'Position',[3.1 figpos(4)-3.9 1 0.5],...
        'String','Right',...
        'Callback',{@offsetRightButton_callback});
    uicontrol(eyeCalfig,'Units','centimeters',...
        'Style','pushbutton',...
        'Tag','gainIncVerButton',...
        'Position',[6.5 figpos(4)-3.4 1 0.5],...
        'String','INC',...
        'Callback',{@gainIncVerButton_callback});
    uicontrol(eyeCalfig,'Units','centimeters',...
        'Style','text',...
        'Position',[6.5 figpos(4)-4 1 0.5],...
        'String','Gain',...
        'BackgroundColor',[0.831 0.816 0.784]);
    uicontrol(eyeCalfig,'Units','centimeters',...
        'Style','pushbutton',...
        'Tag','gainDecVerButton',...
        'Position',[6.5 figpos(4)-4.4 1 0.5],...
        'String','DEC',...
        'Callback',{@gainDecVerButton_callback});
    uicontrol(eyeCalfig,'Units','centimeters',...
        'Style','pushbutton',...
        'Tag','gainDecHorButton',...
        'Position',[5.4 figpos(4)-3.9 1 0.5],...
        'String','DEC',...
        'Callback',{@gainDecHorButton_callback});
    uicontrol(eyeCalfig,'Units','centimeters',...
        'Style','pushbutton',...
        'Tag','gainIncHorButton',...
        'Position',[7.6 figpos(4)-3.9 1 0.5],...
        'String','INC',...
        'Callback',{@gainIncHorButton_callback});
    uicontrol(eyeCalfig,'Units','centimeters',...
        'Style','text',...
        'Position',[0.5 figpos(4)-5.5 3 0.5],...
        'String','Offset Step(deg):',...
        'BackgroundColor',[0.831 0.816 0.784],...
        'HorizontalAlignment', 'Left');
    uicontrol(eyeCalfig,'Units','centimeters',...
        'Style','edit',...
        'Tag','offsetStepEdit',...
        'Position',[3 figpos(4)-5.5 1 0.5],...
        'String',offsetStepstr,...
        'Callback',{@offsetStepEdit_callback},...
        'BackgroundColor','white');
    uicontrol(eyeCalfig,'Units','centimeters',...
        'Style','text',...
        'Position',[5 figpos(4)-5.5 3 0.5],...
        'String','Gain Step(deg/v):',...
        'BackgroundColor',[0.831 0.816 0.784],...
        'HorizontalAlignment', 'Left');
    uicontrol(eyeCalfig,'Units','centimeters',...
        'Style','edit',...
        'Tag','gainStepEdit',...
        'Position',[7.5 figpos(4)-5.5 1 0.5],...
        'String',gainStepstr,...
        'Callback',{@gainStepEdit_callback},...
        'BackgroundColor','white');
    uicontrol(eyeCalfig,'Units','centimeters',...
        'Style','pushbutton',...
        'Tag','targUpButton',...
        'Position',[2 figpos(4)-7.4 1 0.5],...
        'String','UP',...
        'Callback',{@targUpButton_callback});
    uicontrol(eyeCalfig,'Units','centimeters',...
        'Style','text',...
        'Position',[2 figpos(4)-8 1 0.5],...
        'String','Target',...
        'BackgroundColor',[0.831 0.816 0.784]);
    uicontrol(eyeCalfig,'Units','centimeters',...
        'Style','pushbutton',...
        'Tag','targDownButton',...
        'Position',[2 figpos(4)-8.4 1 0.5],...
        'String','Down',...
        'Callback',{@targDownButton_callback});
    uicontrol(eyeCalfig,'Units','centimeters',...
        'Style','pushbutton',...
        'Tag','targLeftButton',...
        'Position',[0.9 figpos(4)-7.9 1 0.5],...
        'String','Left',...
        'Callback',{@targLeftButton_callback});
    uicontrol(eyeCalfig,'Units','centimeters',...
        'Style','pushbutton',...
        'Tag','targRightButton',...
        'Position',[3.1 figpos(4)-7.9 1 0.5],...
        'String','Right',...
        'Callback',{@targRightButton_callback});
    uicontrol(eyeCalfig,'Units','centimeters',...
        'Style','text',...
        'Position',[5 figpos(4)-7.7 3 0.5],...
        'String','Target Step(deg):',...
        'BackgroundColor',[0.831 0.816 0.784],...
        'HorizontalAlignment', 'Left');
    uicontrol(eyeCalfig,'Units','centimeters',...
        'Style','edit',...
        'Tag','targStepEdit',...
        'Position',[7.5 figpos(4)-7.7 1 0.5],...
        'String',targStepstr,...
        'Callback',{@targStepEdit_callback},...
        'BackgroundColor','white');
    uicontrol(eyeCalfig,'Units','centimeters',...
        'Style','pushbutton',...
        'Tag','targResetButton',...
        'Position',[6 figpos(4)-8.4 2 0.5],...
        'String','Target Reset',...
        'Callback',{@targResetButton_callback});
    uicontrol(eyeCalfig,'Units','centimeters',...
        'Style','text',...
        'Position',[0.5 figpos(4)-10 1.5 0.5],...
        'String','Duration(s):',...
        'BackgroundColor',[0.831 0.816 0.784],...
        'HorizontalAlignment', 'Right');
    uicontrol(eyeCalfig,'Units','centimeters',...
        'Style','edit',...
        'Tag','durEdit',...
        'Position',[2.2 figpos(4)-10 1 0.5],...
        'String',durstr,...
        'Callback',{@durationEdit_callback},...
        'BackgroundColor','white');
    uicontrol(eyeCalfig,'Units','centimeters',...
        'Style','text',...
        'Position',[0.5 figpos(4)-11 2.5 0.5],...
        'String','Eye Window(deg):',...
        'BackgroundColor',[0.831 0.816 0.784],...
        'HorizontalAlignment', 'Right');
    uicontrol(eyeCalfig,'Units','centimeters',...
        'Style','edit',...
        'Tag','winSizeEdit',...
        'Position',[3.2 figpos(4)-11 1 0.5],...
        'String',winstr,...
        'Callback',{@winSizeEdit_callback},...
        'BackgroundColor','white');
    uicontrol(eyeCalfig,'Units','centimeters',...
        'Style','text',...
        'Position',[0.5 figpos(4)-12 2.5 0.5],...
        'String','Head Center(cm):',...
        'BackgroundColor',[0.831 0.816 0.784],...
        'HorizontalAlignment', 'Right');
    uicontrol(eyeCalfig,'Units','centimeters',...
        'Style','edit',...
        'Tag','headCenterEdit',...
        'Position',[3.2 figpos(4)-12 2 0.5],...
        'String', headCenterstr,...
        'Callback',{@headCenterEdit_callback},...
        'BackgroundColor','white');
    uicontrol(eyeCalfig,'Units','centimeters',...
        'Style','text',...
        'Position',[0.5 figpos(4)-12.5 2.5 0.5],...
        'String','Eye Offset(cm):',...
        'BackgroundColor',[0.831 0.816 0.784],...
        'HorizontalAlignment', 'Right');
    uicontrol(eyeCalfig,'Units','centimeters',...
        'Style','edit',...
        'Tag','eyeOffsetEdit',...
        'Position',[3.2 figpos(4)-12.5 2 0.5],...
        'String', eyeOffsetstr,...
        'Callback',{@eyeOffsetEdit_callback},...
        'BackgroundColor','white');
    uicontrol(eyeCalfig,'Units','centimeters',...
        'Style','text',...
        'Position',[0.5 figpos(4)-13 2.5 0.5],...
        'String','IO Distance(cm):',...
        'BackgroundColor',[0.831 0.816 0.784],...
        'HorizontalAlignment', 'Right');
    uicontrol(eyeCalfig,'Units','centimeters',...
        'Style','edit',...
        'Tag','ioDistEdit',...
        'Position',[3.2 figpos(4)-13 2 0.5],...
        'String', ioDiststr,...
        'Callback',{@ioDistEdit_callback},...
        'BackgroundColor','white');
    uicontrol(eyeCalfig,'Units','centimeters',...
        'Style','checkbox',...
        'Tag','debugcheckBox',...
        'Position',[8 figpos(4)-12.5 2 0.5],...
        'String','Debug',...
        'BackgroundColor',[0.831 0.816 0.784],...
        'Callback',{@debugcheckBox_callback});
    uicontrol(eyeCalfig,'Units','centimeters',...
        'Style','pushbutton',...
        'Tag','startButton',...
        'Position',[3 0.5 1 0.5],...
        'String','Start',...
        'Callback',{@startButton_callback});
    uicontrol(eyeCalfig,'Units','centimeters',...
        'Style','pushbutton',...
        'Tag','stopButton',...
        'Position',[5 0.5 1 0.5],...
        'String','Stop',...
        'Callback',{@stopButton_callback});

    eyeWinData.tagX = 0;  %deg
    eyeWinData.tagY = 0;  %deg
    eyeWinData.posSmoothPt = str2num(get(findobj(eyeCalfig,'Tag','posSmoothEdit'), 'String'));
    eyeWinData.eyecode = get(findobj(eyeCalfig,'Tag','EyecodePopupMenu'), 'Value')-1;
    eyeWinData.offsetStep = str2num(get(findobj(eyeCalfig,'Tag','offsetStepEdit'), 'String'));
    eyeWinData.gainStep = str2num(get(findobj(eyeCalfig,'Tag','gainStepEdit'), 'String'));
    eyeWinData.targStep = str2num(get(findobj(eyeCalfig,'Tag','targStepEdit'), 'String'));
    eyeWinData.winSize = str2num(get(findobj(eyeCalfig,'Tag','winSizeEdit'), 'String'));
    eyeWinData.headCenter = str2num(get(findobj(eyeCalfig,'Tag','headCenterEdit'), 'String'));
    eyeWinData.eyeOffset = str2num(get(findobj(eyeCalfig,'Tag','eyeOffsetEdit'), 'String'));
    eyeWinData.ioDist = str2num(get(findobj(eyeCalfig,'Tag','ioDistEdit'), 'String'));

    setappdata(eyeCalfig,'eyeWinData',eyeWinData);


    %control loop data initiate
    eyecldata.stage = 'InitializationStage';
    eyecldata.initStage = 1;
    eyecldata.PretrackingTime = 0.1;
    eyecldata.TrackingTime = str2num(get(findobj(eyeCalfig,'Tag','durEdit'), 'String'));
    eyecldata.PostTrackingTime = 0.1;
    eyecldata.beginWav = sin(500*2*pi*(0:.00001:.125));
    eyecldata.correctWav = wavread('C:\WINDOWS\Media\tada.wav');
    eyecldata.wrongWav = wavread('C:\WINDOWS\Media\Windows XP Battery Critical.wav');

    setappdata(eyeCalfig,'eyeControlLoopData',eyecldata);
    
    data.configpath = paths.configpath;
    data.datapath = paths.datapath;
    data.configfile = get(findobj(eyeCalfig,'Tag','ProtEdit'), 'String');
    tmp = importdata([data.configpath filesep data.configfile]);
    data.configinfo = tmp.variables;
    data.channels = tmp.channels;
    data.functions = tmp.functions;
    clear tmp
    % taking out non-active params
    data.configinfo = data.configinfo(cell2mat({data.configinfo.active})==1);
    setappdata(eyeCalfig,'protinfo',data);
end

function watchEyeButton_callback(hobject, event_data)
initWatchEye;

function posSmoothEdit_callback(hobject, event_data)
global eyeCalfig

eyeWinData = getappdata(eyeCalfig,'eyeWinData');
eyeWinData.posSmoothPt = str2num(get(hobject, 'String'));
setappdata(eyeCalfig,'eyeWinData',eyeWinData);

function offsetUpButton_callback(hobject, event_data)
global eyeCalfig
data = getappdata(eyeCalfig,'protinfo'); 
chanInfo = data.channels(cell2mat({data.channels.active})==1); 
eyeWinData = getappdata(eyeCalfig, 'eyeWinData');

if eyeWinData.eyecode 
    chanInfo(5).offset = chanInfo(5).offset + eyeWinData.offsetStep;
    set(findobj('tag',[chanInfo(5).name '-offset']),'string',chanInfo(5).offset);
else
    chanInfo(2).offset = chanInfo(2).offset + eyeWinData.offsetStep;
    set(findobj('tag',[chanInfo(2).name '-offset']),'string',chanInfo(2).offset);
end
data.channels = chanInfo;
setappdata(eyeCalfig,'protinfo', data);   

function offsetDownButton_callback(hobject, event_data)
global eyeCalfig
data = getappdata(eyeCalfig,'protinfo'); 
chanInfo = data.channels(cell2mat({data.channels.active})==1); 
eyeWinData = getappdata(eyeCalfig, 'eyeWinData');

if eyeWinData.eyecode 
    chanInfo(5).offset = chanInfo(5).offset - eyeWinData.offsetStep;
    set(findobj('tag',[chanInfo(5).name '-offset']),'string',chanInfo(5).offset);
else
    chanInfo(2).offset = chanInfo(2).offset - eyeWinData.offsetStep; 
    set(findobj('tag',[chanInfo(2).name '-offset']),'string',chanInfo(2).offset);
end
data.channels = chanInfo;
setappdata(eyeCalfig,'protinfo', data);   

function offsetLeftButton_callback(hobject, event_data)
global eyeCalfig
data = getappdata(eyeCalfig,'protinfo'); 
chanInfo = data.channels(cell2mat({data.channels.active})==1); 
eyeWinData = getappdata(eyeCalfig, 'eyeWinData');

if eyeWinData.eyecode 
    chanInfo(4).offset = chanInfo(4).offset - eyeWinData.offsetStep;
    set(findobj('tag',[chanInfo(4).name '-offset']),'string',chanInfo(4).offset);
else
    chanInfo(1).offset = chanInfo(1).offset - eyeWinData.offsetStep; 
    set(findobj('tag',[chanInfo(1).name '-offset']),'string',chanInfo(1).offset);
end
data.channels = chanInfo;
setappdata(eyeCalfig,'protinfo', data);  

function offsetRightButton_callback(hobject, event_data)
global eyeCalfig
data = getappdata(eyeCalfig,'protinfo'); 
chanInfo = data.channels(cell2mat({data.channels.active})==1); 
eyeWinData = getappdata(eyeCalfig, 'eyeWinData');

if eyeWinData.eyecode 
    chanInfo(4).offset = chanInfo(4).offset + eyeWinData.offsetStep;
    set(findobj('tag',[chanInfo(4).name '-offset']),'string',chanInfo(4).offset);
else
    chanInfo(1).offset = chanInfo(1).offset + eyeWinData.offsetStep; 
    set(findobj('tag',[chanInfo(1).name '-offset']),'string',chanInfo(1).offset);
end
data.channels = chanInfo;
setappdata(eyeCalfig,'protinfo', data);  

function gainIncVerButton_callback(hobject, event_data)
global eyeCalfig
data = getappdata(eyeCalfig,'protinfo'); 
chanInfo = data.channels(cell2mat({data.channels.active})==1); 
eyeWinData = getappdata(eyeCalfig, 'eyeWinData');

if eyeWinData.eyecode
    chanInfo(5).scale = chanInfo(5).scale + eyeWinData.gainStep;
    set(findobj('tag',[chanInfo(5).name '-gain']),'string',chanInfo(5).scale);
else
    chanInfo(2).scale = chanInfo(2).scale + eyeWinData.gainStep;
    set(findobj('tag',[chanInfo(2).name '-gain']),'string',chanInfo(2).scale);
end
    
data.channels = chanInfo;
setappdata(eyeCalfig,'protinfo', data);  

function gainDecVerButton_callback(hobject, event_data)
global eyeCalfig
data = getappdata(eyeCalfig,'protinfo'); 
chanInfo = data.channels(cell2mat({data.channels.active})==1); 
eyeWinData = getappdata(eyeCalfig, 'eyeWinData');

if eyeWinData.eyecode
    chanInfo(5).scale = chanInfo(5).scale - eyeWinData.gainStep;
    set(findobj('tag',[chanInfo(5).name '-gain']),'string',chanInfo(5).scale);
else
    chanInfo(2).scale = chanInfo(2).scale - eyeWinData.gainStep;
    set(findobj('tag',[chanInfo(2).name '-gain']),'string',chanInfo(2).scale);
end

data.channels = chanInfo;
setappdata(eyeCalfig,'protinfo', data);  

function gainDecHorButton_callback(hobject, event_data)
global eyeCalfig
data = getappdata(eyeCalfig,'protinfo'); 
chanInfo = data.channels(cell2mat({data.channels.active})==1); 
eyeWinData = getappdata(eyeCalfig, 'eyeWinData');

if eyeWinData.eyecode
    chanInfo(4).scale = chanInfo(4).scale - eyeWinData.gainStep;
    set(findobj('tag',[chanInfo(4).name '-gain']),'string',chanInfo(4).scale);
else
    chanInfo(1).scale = chanInfo(1).scale - eyeWinData.gainStep;
    set(findobj('tag',[chanInfo(1).name '-gain']),'string',chanInfo(1).scale);
end

data.channels = chanInfo;
setappdata(eyeCalfig,'protinfo', data);  

function gainIncHorButton_callback(hobject, event_data)
global eyeCalfig
data = getappdata(eyeCalfig,'protinfo'); 
chanInfo = data.channels(cell2mat({data.channels.active})==1); 
eyeWinData = getappdata(eyeCalfig, 'eyeWinData');

if eyeWinData.eyecode
    chanInfo(4).scale = chanInfo(4).scale + eyeWinData.gainStep;
    set(findobj('tag',[chanInfo(4).name '-gain']),'string',chanInfo(4).scale);
else
    chanInfo(1).scale = chanInfo(1).scale + eyeWinData.gainStep;
    set(findobj('tag',[chanInfo(1).name '-gain']),'string',chanInfo(1).scale);
end

data.channels = chanInfo;
setappdata(eyeCalfig,'protinfo', data);  

function offsetStepEdit_callback(hobject, event_data)
global eyeCalfig

eyeWinData = getappdata(eyeCalfig,'eyeWinData');
eyeWinData.offsetStep = str2num(get(hobject, 'String'));
setappdata(eyeCalfig,'eyeWinData',eyeWinData);

function gainStepEdit_callback(hobject, event_data)
global eyeCalfig

eyeWinData = getappdata(eyeCalfig,'eyeWinData');
eyeWinData.gainStep = str2num(get(hobject, 'String'));
setappdata(eyeCalfig,'eyeWinData',eyeWinData);

function eyecodePopupMenu_callback(hobject, event_data)
global eyeCalfig

eyeWinData = getappdata(eyeCalfig,'eyeWinData');
eyeWinData.eyecode = get(hobject, 'Value')-1;
setappdata(eyeCalfig,'eyeWinData',eyeWinData);

function targUpButton_callback(hobject, event_data)
global eyeCalfig
eyeWinData = getappdata(eyeCalfig,'eyeWinData');

tagY = eyeWinData.tagY+eyeWinData.targStep;
if tagY > 30
    tagY = 0;
end
eyeWinData.tagY = tagY;
setappdata(eyeCalfig,'eyeWinData',eyeWinData);


function targDownButton_callback(hobject, event_data)
global eyeCalfig
eyeWinData = getappdata(eyeCalfig,'eyeWinData');

tagY = eyeWinData.tagY-eyeWinData.targStep;
if tagY < -30
    tagY = 0;
end
eyeWinData.tagY = tagY;
setappdata(eyeCalfig,'eyeWinData',eyeWinData);


function targLeftButton_callback(hobject, event_data)
global eyeCalfig
eyeWinData = getappdata(eyeCalfig,'eyeWinData');

tagX = eyeWinData.tagX-eyeWinData.targStep;
if tagX < -30
    tagX = 0;
end
eyeWinData.tagX = tagX;
setappdata(eyeCalfig,'eyeWinData',eyeWinData);

function targRightButton_callback(hobject, event_data)
global eyeCalfig
eyeWinData = getappdata(eyeCalfig,'eyeWinData');

tagX = eyeWinData.tagX+eyeWinData.targStep;
if tagX > 30
    tagX = 0;
end
eyeWinData.tagX = tagX;
setappdata(eyeCalfig,'eyeWinData',eyeWinData);


function targStepEdit_callback(hobject, event_data)
global eyeCalfig

eyeWinData = getappdata(eyeCalfig,'eyeWinData');
eyeWinData.targStep = str2num(get(hobject, 'String'));
setappdata(eyeCalfig,'eyeWinData',eyeWinData);

function targResetButton_callback(hobject, event_data)
global eyeCalfig
eyeWinData = getappdata(eyeCalfig,'eyeWinData');

eyeWinData.tagX = 0;
eyeWinData.tagY = 0;

setappdata(eyeCalfig,'eyeWinData',eyeWinData);

function durationEdit_callback(hobject, event_data)
global eyeCalfig

eyecldata = getappdata(eyeCalfig,'eyeControlLoopData');
eyecldata.duration = str2num(get(hobject, 'String'));
setappdata(eyeCalfig,'eyeControlLoopData',eyecldata);

function winSizeEdit_callback(hobject, event_data)
global eyeCalfig

eyeWinData = getappdata(eyeCalfig,'eyeWinData');
eyeWinData.winSize = str2num(get(hobject, 'String'));
setappdata(eyeCalfig,'eyeWinData',eyeWinData);

function headCenterEdit_callback(hobject, event_data)
global eyeCalfig

eyeWinData = getappdata(eyeCalfig,'eyeWinData');
eyeWinData.headCenter = str2num(get(hobject, 'String'));
setappdata(eyeCalfig,'eyeWinData',eyeWinData);

function eyeOffsetEdit_callback(hobject, event_data)
global eyeCalfig

eyeWinData = getappdata(eyeCalfig,'eyeWinData');
eyeWinData.eyeOffset = str2num(get(hobject, 'String'));
setappdata(eyeCalfig,'eyeWinData',eyeWinData);

function ioDistEdit_callback(hobject, event_data)
global eyeCalfig

eyeWinData = getappdata(eyeCalfig,'eyeWinData');
eyeWinData.ioDist = str2num(get(hobject, 'String'));
setappdata(eyeCalfig,'eyeWinData',eyeWinData);

function debugcheckBox_callback(hobject, event_data)
global debug

debug = get(hobject, 'Value');
if debug
    DebugWindow;
else
    hDebug = findobj('Name','Debug Window');
    if ~isempty(hDebug)
        close(hDebug);
    end
end

function startButton_callback(hobject, event_data)
global eyeCalfig connected

if connected
    initServer
end

% Define a timer.
period = .001;
delete(timerfind('Tag','eyeCLoop'));
CLoop = timer('TimerFcn',{@eyeCalibrationControlLoop eyeCalfig},...
              'Period',period,'Tag','eyeCLoop','ExecutionMode','fixedRate');

%  Start Control Loop
run = get(timerfind('Tag','eyeCLoop'),'Running');
if strmatch(run,'off','exact')
    start(CLoop);
else
    disp('Control Loop already running');
end
setappdata(eyeCalfig,'Timer',CLoop);


function stopButton_callback(hobject, event_data)
global eyeCalfig
eyeDataSampleObj = getappdata(eyeCalfig, 'eyeDataSample');

stop(getappdata(eyeCalfig,'Timer'));
cbStopBackground(eyeDataSampleObj.boardNum, eyeDataSampleObj.AIFUNCTION);
 


data = getappdata(eyeCalfig,'protinfo');
eyeWinData = getappdata(eyeCalfig,'eyeWinData');

tmpStru.headCenter = eyeWinData.headCenter;
tmpStru.eyeOffset = eyeWinData.eyeOffset;
tmpStru.ioDist = eyeWinData.ioDist;
tmpStru.eyecode = eyeWinData.eyecode;


savedInfo.channels = data.channels(1:6);
savedInfo.subject = tmpStru;

a = clock;
timestr = [num2str(a(4)) ',' num2str(a(5))];
[filename, pathname] = uiputfile('*.mat', 'Save Data',...
    [data.datapath filesep 'calibration_' char(date) '_' char(timestr)]);
if ~isequal(filename, 0) && ~isequal(pathname, 0)
    save([pathname, filename], 'savedInfo');
    disp(['saving ' pathname filename])
else
    disp('Save Unsuccesful')
end

function EyeCalibration_CloseRequestFcn(hobject, event_data)
global debug

debug = 0;

delete(hobject);

H = findobj('Name','Watch Eyes');
if ~isempty(H)
    delete(H)
end

H = findobj('Name','Debug Window');
if ~isempty(H)
    delete(H)
end

H = findobj('Name','Eye Options');
if ~isempty(H)
    delete(H)
end

H = findobj('Name','BasicInterface');
if ~isempty(H)
    set(H,'Visible','On');
end





